### ISSUE TITLE
embedded filesystem limitation

### ISSUE THREAD

**Issue by kbenne** [NREL/Spawn#33]
It appears that some special characters cause trouble. I think this is addressed for OpenStudio's embedded filesystem so it might be worth a look there.

|| /bin/sh: 1: Syntax error: "(" unexpected
make[2]: *** [cli/CMakeFiles/spawn.dir/build.make|5075| cli/embedded_files/JModelica/ThirdParty/MSL/Modelica/Resources/Images/Magnetic/QuasiStatic/FundamentalWave/Phi(ref)=Phi,re+jPhi,im_png.cxx] Error 2

In order to reproduce this, just build the "compiler_hook" branch with the MSL lines uncommented. https://github.com/NREL/Spawn/blob/compiler_hook/cli/CMakeLists.txt#L154

**Comment by lefticus** [comment]
@kbenne has compiler_hook been merged into develop?
