### ISSUE TITLE
llvm / clang linking to shared libs

### ISSUE THREAD

**Issue by kbenne** [NREL/Spawn#34]
Hey @lefticus 

I noticed that the cmake rules are linking to the llvm and clang shared libraries. This isn't the end of the world. I could use fixup_bundle to install these with our end user distribution package. But I would prefer to link to the archive libraries. 

I think the issue stems from these link commands https://github.com/NREL/Spawn/blob/49508dffa0e96cf032b0355f416eeb596974461e/compiler/CMakeLists.txt#L75. We are using the llvm provided cmake export libraries and those targets currently map to the shared libs. I wonder if there are alternative export lib targets for the archive libraries, or if we can configure how this works with a flag. 

I parsed through llvm-8's lib directory and the archive libs are certainly there, but I think it might be that one shared lib maps to many archives. 

Do you think you could research this?

**Comment by kbenne** [comment]
kbenne@darth-vader:~/Development/spawn/build-release$ ldd cli/spawn
        linux-vdso.so.1 (0x00007ffeff1fe000)
        jmodelica.so => /home/kbenne/Development/spawn/build-release/cli/jmodelica.so (0x00007efc4472f000)
        optimica.so => /home/kbenne/Development/spawn/build-release/cli/optimica.so (0x00007efc40f13000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc40ed0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efc40eca000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efc40ce9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc40b9a000)
        libLLVM-8.so.1 => /usr/lib/llvm-8/lib/libLLVM-8.so.1 (0x00007efc3cf74000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efc3cf59000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc3cd67000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efc4d119000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efc3cd4b000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007efc3cd3f000)
        libedit.so.2 => /lib/x86_64-linux-gnu/libedit.so.2 (0x00007efc3cd05000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007efc3ccfa000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007efc3ccca000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007efc3ccb0000)

**Comment by kbenne** [comment]
@lefticus on more thing. I think the "jmodelica" branch is in a good point to work from. https://github.com/NREL/Spawn/tree/jmodelica

**Comment by lefticus** [comment]
My `ldd` agrees with yours. We are statically linking to as many things as we can (`clang*.a`) and dynamically linking to the one thing we cannot statically link: `libLLVM`. 

We can see in the clang CMake where this comes in: 

![image](https://user-images.githubusercontent.com/234279/125547775-5a1e36f4-9f11-4202-b8d7-da4347ff87b9.png)

There is no way to work around this that I can see. (at least with the system provided libraries/cmake)

Unfortunately this seems to be a rather large .so file

![image](https://user-images.githubusercontent.com/234279/125548040-09d1c025-af00-4fc6-8ee8-b3cd5fc492ce.png)
