### ISSUE TITLE
Job Failed #571837550

### ISSUE THREAD

**Issue by kbenne** [NREL/Spawn#4]
Job [#571837550](https://gitlab.com/kylebenne/spawn/-/jobs/571837550) failed for b0974853d7a84a0886a02a8f810a535e8a153b98:

This test fails because the unzipper doesn't see the epfmi.dll. The thing is that I checked and it sure appears to be there with that name, so I'm not immediately sure what the issue is. @lefticus Can you take a look when you are next working in this area?

**Comment by lefticus** [comment]
I think it might be a slashes issues. I'll look into it. I probably forgot to test on Windows.

**Comment by kbenne** [comment]
resolved.
