### ISSUE TITLE
exeDir() is not robust

### ISSUE THREAD

**Issue by kbenne** [NREL/Spawn#5]
There are a variety of circumstances where the spawn cli needs to know where it is located in order to find supporting resources. The current logic to perform this function is here https://github.com/NREL/Spawn/blob/b47b0c49cabe76f073ed5d16f2e3b6c7b51de2bc/cli/main.cpp#L30. The problem is that this is not robust for some cases including at least

1. Spawn is installed into the system PATH and is invoked from the command line generically as `spawn`. (no full path)
2. The `spawn` cli is called from a link.

It might be that 1 and 2 may exist. At least on Linux Spawn is not robust to these cases.

**Comment by lefticus** [comment]
Is there any automated test for this, or can you think of one that would work?

**Comment by kbenne** [comment]
What about using setenv to define the path where spawn exe is located? Then make a system call `spawn --version`
